SET NOCOUNT ON
SET TRAN ISOLATION LEVEL READ UNCOMMITTED

DROP TABLE IF EXISTS #ModifiedDates
CREATE TABLE #ModifiedDates (SchemaName sysname, TableName sysname, MaxModifiedDate DATETIME)

INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveReturnBackLookup', COUNT(1) FROM AccountsPayable.IncentiveReturnBackLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveReturnLookup', COUNT(1) FROM AccountsPayable.IncentiveReturnLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveTypeLookup', COUNT(1) FROM AccountsPayable.IncentiveTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorShipmentOriginLookup', COUNT(1) FROM AccountsPayable.VendorShipmentOriginLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorStockTypeLookup', COUNT(1) FROM AccountsPayable.VendorStockTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderDiscountLevel', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderDiscountLevel
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorToVendorStockTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorToVendorStockTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderReceiptGroup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderReceiptGroup
/*
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderReceiptGroupStatusLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderReceiptGroupStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorLevelUpLookup', MAX(DateUpdated) FROM AccountsPayable.VendorLevelUpLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','Vendor1099StatusLookup', MAX(DateUpdated) FROM AccountsPayable.Vendor1099StatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderFreightAllocationMethodLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderFreightAllocationMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorBackorderTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorBackorderTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorRebateIncentive', MAX(DateUpdated) FROM AccountsPayable.VendorRebateIncentive
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorRebateProgram', MAX(DateUpdated) FROM AccountsPayable.VendorRebateProgram
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorRebateProgramProjectedPercentage', MAX(DateUpdated) FROM AccountsPayable.VendorRebateProgramProjectedPercentage
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorRebateProgramTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorRebateProgramTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PaymentMethodLookup', MAX(DateUpdated) FROM AccountsPayable.PaymentMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorRebateDocument', MAX(DateUpdated) FROM AccountsPayable.VendorRebateDocument
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorToVendorRebateDocument', MAX(DateUpdated) FROM AccountsPayable.VendorToVendorRebateDocument
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrder', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrder
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorToVendorRebateProgram', MAX(DateUpdated) FROM AccountsPayable.VendorToVendorRebateProgram
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderDestination', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderDestination
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderLine', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderLineStatusLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderLineStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderReceipt', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderReceipt
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderReceiptLine', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderReceiptLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderReceiptLineToSerialNumber', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderReceiptLineToSerialNumber
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderPriceModifierTypeLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderPriceModifierTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderStatusLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoicePriceModifier', MAX(DateUpdated) FROM AccountsPayable.VendorInvoicePriceModifier
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderTypeLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','Vendor', MAX(DateUpdated) FROM AccountsPayable.Vendor
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoicePriceModifierLookup', MAX(DateUpdated) FROM AccountsPayable.VendorInvoicePriceModifierLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoice', MAX(DateUpdated) FROM AccountsPayable.VendorInvoice
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceLine', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceShortPayPriceModifierTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceShortPayPriceModifierTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceStatusLookup', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceShortPay', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceShortPay
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceShortPayReasonLookup', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceShortPayReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorInvoiceTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorInvoiceTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorToAddress', MAX(DateUpdated) FROM AccountsPayable.VendorToAddress
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorToContact', MAX(DateUpdated) FROM AccountsPayable.VendorToContact
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','VendorTypeLookup', MAX(DateUpdated) FROM AccountsPayable.VendorTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderBackorderedActionLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderBackorderedActionLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderFreightDistributionLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderFreightDistributionLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderLineToPurchaseOrderShipmentLine', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderLineToPurchaseOrderShipmentLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderShipment', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderShipment
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderShipmentLine', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderShipmentLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderShipmentLineStatusLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderShipmentLineStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','PurchaseOrderShipmentStatusLookup', MAX(DateUpdated) FROM AccountsPayable.PurchaseOrderShipmentStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveBaseForGrowthLookup', MAX(DateUpdated) FROM AccountsPayable.IncentiveBaseForGrowthLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveCaseTypeLookup', MAX(DateUpdated) FROM AccountsPayable.IncentiveCaseTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveDateTypeLookup', MAX(DateUpdated) FROM AccountsPayable.IncentiveDateTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentiveMeasuredByTypeLookup', MAX(DateUpdated) FROM AccountsPayable.IncentiveMeasuredByTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsPayable','IncentivePurchaseBasisLookup', MAX(DateUpdated) FROM AccountsPayable.IncentivePurchaseBasisLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','PaymentTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.PaymentTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','TaxClassificationGroup', MAX(DateUpdated) FROM AccountsReceivable.TaxClassificationGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderShipmentAuthorizationStatusReasonLookup', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderShipmentAuthorizationStatusReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderPaymentAuthorization', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderPaymentAuthorization
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','TaxClassification', MAX(DateUpdated) FROM AccountsReceivable.TaxClassification
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','ShipmentRouteLookup', MAX(DateUpdated) FROM AccountsReceivable.ShipmentRouteLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','ShipmentRegulationTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.ShipmentRegulationTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','ShipmentTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.ShipmentTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderShipmentAuthorizationStatusLookup', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderShipmentAuthorizationStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderStatusLookup', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderLine', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderLineStatusLookup', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderLineStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderShipmentAuthorization', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderShipmentAuthorization
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesTaxInformationHeader', MAX(DateUpdated) FROM AccountsReceivable.SalesTaxInformationHeader
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerStatementNotificationLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerStatementNotificationLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerStateLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerStateLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesTaxInformationLine', MAX(DateUpdated) FROM AccountsReceivable.SalesTaxInformationLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrder', MAX(DateUpdated) FROM AccountsReceivable.SalesOrder
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceStatusLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceShipmentLine', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceShipmentLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceShipmentLineToItemSerialNumber', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceShipmentLineToItemSerialNumber
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceShipment', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceShipment
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoiceLine', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoiceLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerInvoice', MAX(DateUpdated) FROM AccountsReceivable.CustomerInvoice
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','Customer', MAX(DateUpdated) FROM AccountsReceivable.Customer
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderShipmentAuthorizationSnapshot', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderShipmentAuthorizationSnapshot
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerParentToContactTypeLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerParentToContactTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerParentToContact', MAX(DateUpdated) FROM AccountsReceivable.CustomerParentToContact
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerParentStateLookup', MAX(DateUpdated) FROM AccountsReceivable.CustomerParentStateLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','CustomerParent', MAX(DateUpdated) FROM AccountsReceivable.CustomerParent
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderLineToSerialNumber', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderLineToSerialNumber
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesTaxJurisdictionResultToCustomerInvoiceLine', MAX(DateUpdated) FROM AccountsReceivable.SalesTaxJurisdictionResultToCustomerInvoiceLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesTaxJurisdictionResult', MAX(DateUpdated) FROM AccountsReceivable.SalesTaxJurisdictionResult
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderLineChange', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderLineChange
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderLineSnapshot', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderLineSnapshot
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderSnapshot', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderSnapshot
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','SalesOrderShipmentAuthorizationDisallowedShipDay', MAX(DateUpdated) FROM AccountsReceivable.SalesOrderShipmentAuthorizationDisallowedShipDay
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','DataSourceReasonLookup', MAX(DateUpdated) FROM AccountsReceivable.DataSourceReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'AccountsReceivable','TaxClassificationSubGroup', MAX(DateUpdated) FROM AccountsReceivable.TaxClassificationSubGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','AccountTypeLookup', MAX(DateUpdated) FROM Financial.AccountTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Calendar', MAX(DateUpdated) FROM Financial.Calendar
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Account', MAX(DateUpdated) FROM Financial.Account
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ChartOfAccounts', MAX(DateUpdated) FROM Financial.ChartOfAccounts
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','PeriodTypeLookup', MAX(DateUpdated) FROM Financial.PeriodTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Period', MAX(DateUpdated) FROM Financial.Period
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','PeriodStatusLookup', MAX(DateUpdated) FROM Financial.PeriodStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalLineSourceTypeLookup', MAX(DateUpdated) FROM Financial.JournalLineSourceTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalLineTypeLookup', MAX(DateUpdated) FROM Financial.JournalLineTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Year', MAX(DateUpdated) FROM Financial.Year
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','PaymentTypeToAccount', MAX(DateUpdated) FROM Financial.PaymentTypeToAccount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerPostingType', MAX(DateUpdated) FROM Financial.LedgerPostingType
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportControl', MAX(DateUpdated) FROM Financial.ReportControl
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerPostingIntercompany', MAX(DateUpdated) FROM Financial.LedgerPostingIntercompany
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalTypeLookup', MAX(DateUpdated) FROM Financial.JournalTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalStatusLookup', MAX(DateUpdated) FROM Financial.JournalStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportType', MAX(DateUpdated) FROM Financial.ReportType
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportLine', MAX(DateUpdated) FROM Financial.ReportLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerPostError', MAX(DateUpdated) FROM Financial.LedgerPostError
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerPost', MAX(DateUpdated) FROM Financial.LedgerPost
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportLineAccount', MAX(DateUpdated) FROM Financial.ReportLineAccount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportGroupTotalText', MAX(DateUpdated) FROM Financial.ReportGroupTotalText
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','ReportGroup', MAX(DateUpdated) FROM Financial.ReportGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','YearCloseLedger', MAX(DateUpdated) FROM Financial.YearCloseLedger
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerSummary', MAX(DateUpdated) FROM Financial.LedgerSummary
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','LedgerPostingTypeToAccount', MAX(DateUpdated) FROM Financial.LedgerPostingTypeToAccount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','InventoryAdjustmentPostingType', MAX(DateUpdated) FROM Financial.InventoryAdjustmentPostingType
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalLine', MAX(DateUpdated) FROM Financial.JournalLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalLedgerGroup', MAX(DateUpdated) FROM Financial.JournalLedgerGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Journal', MAX(DateUpdated) FROM Financial.Journal
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','JournalSource', MAX(DateUpdated) FROM Financial.JournalSource
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Financial','Ledger', MAX(DateUpdated) FROM Financial.Ledger
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','PaymentTermSchedule', MAX(DateUpdated) FROM IDS.PaymentTermSchedule
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Contact', MAX(DateUpdated) FROM IDS.Contact
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Address', MAX(DateUpdated) FROM IDS.Address
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Company', MAX(DateUpdated) FROM IDS.Company
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Country', MAX(DateUpdated) FROM IDS.Country
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','DiscountTerm', MAX(DateUpdated) FROM IDS.DiscountTerm
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','CostCenter', MAX(DateUpdated) FROM IDS.CostCenter
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','LocationGroup', MAX(DateUpdated) FROM IDS.LocationGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','SalesChannel', MAX(DateUpdated) FROM IDS.SalesChannel
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','LocationToLocationGroup', MAX(DateUpdated) FROM IDS.LocationToLocationGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Organization', MAX(DateUpdated) FROM IDS.Organization
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','Location', MAX(DateUpdated) FROM IDS.Location
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','LocationTypeLookup', MAX(DateUpdated) FROM IDS.LocationTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','IdsUser', MAX(DateUpdated) FROM IDS.IdsUser
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','PaymentTerm', MAX(DateUpdated) FROM IDS.PaymentTerm
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','SourceSystemLookup', MAX(DateUpdated) FROM IDS.SourceSystemLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','State', MAX(DateUpdated) FROM IDS.State
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'IDS','DayLookup', MAX(DateUpdated) FROM IDS.DayLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveLineStatusLookup', MAX(DateUpdated) FROM Inventory.PickWaveLineStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveTransferLineToInventoryControlAction', MAX(DateUpdated) FROM Inventory.PickWaveTransferLineToInventoryControlAction
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinTypeLookup', MAX(DateUpdated) FROM Inventory.BinTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveStatusLookup', MAX(DateUpdated) FROM Inventory.PickWaveStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','Bin', MAX(DateUpdated) FROM Inventory.Bin
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveLineItemVerification', MAX(DateUpdated) FROM Inventory.PickWaveLineItemVerification
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveLineItemVerificationMethodLookup', MAX(DateUpdated) FROM Inventory.PickWaveLineItemVerificationMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveTransferLine', MAX(DateUpdated) FROM Inventory.PickWaveTransferLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryControlTypeLookup', MAX(DateUpdated) FROM Inventory.InventoryControlTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryControlReasonLookup', MAX(DateUpdated) FROM Inventory.InventoryControlReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveLineToInventoryControlAction', MAX(DateUpdated) FROM Inventory.PickWaveLineToInventoryControlAction
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveLine', MAX(DateUpdated) FROM Inventory.PickWaveLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryControlCompletionReasonLookup', MAX(DateUpdated) FROM Inventory.InventoryControlCompletionReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemSalesChannel', MAX(DateUpdated) FROM Inventory.ItemSalesChannel
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWave', MAX(DateUpdated) FROM Inventory.PickWave
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SalePricingTypeLookup', MAX(DateUpdated) FROM Inventory.SalePricingTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickingMethodLookup', MAX(DateUpdated) FROM Inventory.PickingMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryControlAction', MAX(DateUpdated) FROM Inventory.InventoryControlAction
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','Brand', MAX(DateUpdated) FROM Inventory.Brand
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemStockSignificanceLookup', MAX(DateUpdated) FROM Inventory.ItemStockSignificanceLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','OrderPickGroupStatusLookup', MAX(DateUpdated) FROM Inventory.OrderPickGroupStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','OrderPickGroupLineToSalesOrderLine', MAX(DateUpdated) FROM Inventory.OrderPickGroupLineToSalesOrderLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitTransactionLine', MAX(DateUpdated) FROM Inventory.KitTransactionLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinTransferBatchSourceLookup', MAX(DateUpdated) FROM Inventory.BinTransferBatchSourceLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationStock', MAX(DateUpdated) FROM Inventory.ItemLocationStock
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','OrderPickGroupToSalesOrderShipmentAuthorization', MAX(DateUpdated) FROM Inventory.OrderPickGroupToSalesOrderShipmentAuthorization
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemFulfillmentInformation', MAX(DateUpdated) FROM Inventory.ItemFulfillmentInformation
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemReference', MAX(DateUpdated) FROM Inventory.ItemReference
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemRelationship', MAX(DateUpdated) FROM Inventory.ItemRelationship
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemSerialNumber', MAX(DateUpdated) FROM Inventory.ItemSerialNumber
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemRelationshipTypeLookup', MAX(DateUpdated) FROM Inventory.ItemRelationshipTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemSerialNumberStatusLookup', MAX(DateUpdated) FROM Inventory.ItemSerialNumberStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBlend', MAX(DateUpdated) FROM Inventory.ItemBlend
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BarcodeUnitTypeLookup', MAX(DateUpdated) FROM Inventory.BarcodeUnitTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransferOrderTypeLookup', MAX(DateUpdated) FROM Inventory.TransferOrderTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','StorageMediaLookup', MAX(DateUpdated) FROM Inventory.StorageMediaLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationReplenishment', MAX(DateUpdated) FROM Inventory.ItemLocationReplenishment
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationRecentActivity', MAX(DateUpdated) FROM Inventory.ItemLocationRecentActivity
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationPrice', MAX(DateUpdated) FROM Inventory.ItemLocationPrice
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBarcode', MAX(DateUpdated) FROM Inventory.ItemBarcode
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SerializedItemsLookup', MAX(DateUpdated) FROM Inventory.SerializedItemsLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemCatalog', MAX(DateUpdated) FROM Inventory.ItemCatalog
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationItemVendorOverride', MAX(DateUpdated) FROM Inventory.ItemLocationItemVendorOverride
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','PickWaveTypeLookup', MAX(DateUpdated) FROM Inventory.PickWaveTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BreakdownCategoryLookup', MAX(DateUpdated) FROM Inventory.BreakdownCategoryLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','Item', MAX(DateUpdated) FROM Inventory.Item
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocation', MAX(DateUpdated) FROM Inventory.ItemLocation
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SalePricingCampaign', MAX(DateUpdated) FROM Inventory.SalePricingCampaign
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransferOrderLine', MAX(DateUpdated) FROM Inventory.TransferOrderLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ClimateControlledLookup', MAX(DateUpdated) FROM Inventory.ClimateControlledLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemGroup', MAX(DateUpdated) FROM Inventory.ItemGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransferOrder', MAX(DateUpdated) FROM Inventory.TransferOrder
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinProfile', MAX(DateUpdated) FROM Inventory.BinProfile
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemLocationBinStock', MAX(DateUpdated) FROM Inventory.ItemLocationBinStock
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','CycleCountTypeLookup', MAX(DateUpdated) FROM Inventory.CycleCountTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBreakdown', MAX(DateUpdated) FROM Inventory.ItemBreakdown
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SalePricingEntry', MAX(DateUpdated) FROM Inventory.SalePricingEntry
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransferOrderStatusLookup', MAX(DateUpdated) FROM Inventory.TransferOrderStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','StockTypeLookup', MAX(DateUpdated) FROM Inventory.StockTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementTaskStatusLookup', MAX(DateUpdated) FROM Inventory.MovementTaskStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementTaskPicking', MAX(DateUpdated) FROM Inventory.MovementTaskPicking
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemWarranty', MAX(DateUpdated) FROM Inventory.ItemWarranty
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinTransferLine', MAX(DateUpdated) FROM Inventory.BinTransferLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','CycleCountLine', MAX(DateUpdated) FROM Inventory.CycleCountLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','OrderPickGroup', MAX(DateUpdated) FROM Inventory.OrderPickGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','CycleCount', MAX(DateUpdated) FROM Inventory.CycleCount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinTransferBatch', MAX(DateUpdated) FROM Inventory.BinTransferBatch
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','OrderPickGroupLine', MAX(DateUpdated) FROM Inventory.OrderPickGroupLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','CycleCountStatusLookup', MAX(DateUpdated) FROM Inventory.CycleCountStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitTransaction', MAX(DateUpdated) FROM Inventory.KitTransaction
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','BinTransferStatusLookup', MAX(DateUpdated) FROM Inventory.BinTransferStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementLoadLookup', MAX(DateUpdated) FROM Inventory.MovementLoadLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementPickWaveStatusLookup', MAX(DateUpdated) FROM Inventory.MovementPickWaveStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','WarrantyCoverageLookup', MAX(DateUpdated) FROM Inventory.WarrantyCoverageLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementPickWave', MAX(DateUpdated) FROM Inventory.MovementPickWave
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementTask', MAX(DateUpdated) FROM Inventory.MovementTask
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementPickWaveTypeLookup', MAX(DateUpdated) FROM Inventory.MovementPickWaveTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','WarrantyProviderLookup', MAX(DateUpdated) FROM Inventory.WarrantyProviderLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemWarrantyContactLookup', MAX(DateUpdated) FROM Inventory.ItemWarrantyContactLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementJob', MAX(DateUpdated) FROM Inventory.MovementJob
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementDiscrepancyReasonLookup', MAX(DateUpdated) FROM Inventory.MovementDiscrepancyReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementJobPicking', MAX(DateUpdated) FROM Inventory.MovementJobPicking
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementJobStatusLookup', MAX(DateUpdated) FROM Inventory.MovementJobStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemPricing', MAX(DateUpdated) FROM Inventory.ItemPricing
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SellPriceQuantityDiscountTypeLookup', MAX(DateUpdated) FROM Inventory.SellPriceQuantityDiscountTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','StockingMethodLookup', MAX(DateUpdated) FROM Inventory.StockingMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementAction', MAX(DateUpdated) FROM Inventory.MovementAction
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','UnitLookup', MAX(DateUpdated) FROM Inventory.UnitLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementActionLookup', MAX(DateUpdated) FROM Inventory.MovementActionLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','Zone', MAX(DateUpdated) FROM Inventory.Zone
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitRecipeTypeLookup', MAX(DateUpdated) FROM Inventory.KitRecipeTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','MovementReasonLookup', MAX(DateUpdated) FROM Inventory.MovementReasonLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','QualityCheckTypeLookup', MAX(DateUpdated) FROM Inventory.QualityCheckTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryAdjustmentBatch', MAX(DateUpdated) FROM Inventory.InventoryAdjustmentBatch
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransactionLog', MAX(DateUpdated) FROM Inventory.TransactionLog
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ReplenishmentTypeLookup', MAX(DateUpdated) FROM Inventory.ReplenishmentTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','InventoryAdjustmentLine', MAX(DateUpdated) FROM Inventory.InventoryAdjustmentLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitRecipe', MAX(DateUpdated) FROM Inventory.KitRecipe
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','TransactionLogSourceTypeLookup', MAX(DateUpdated) FROM Inventory.TransactionLogSourceTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','SellPriceQuantityDiscount', MAX(DateUpdated) FROM Inventory.SellPriceQuantityDiscount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemStateLookup', MAX(DateUpdated) FROM Inventory.ItemStateLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBlendInventoryManagement', MAX(DateUpdated) FROM Inventory.ItemBlendInventoryManagement
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBlendAudit', MAX(DateUpdated) FROM Inventory.ItemBlendAudit
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemTypeLookup', MAX(DateUpdated) FROM Inventory.ItemTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemBlendStatusLookup', MAX(DateUpdated) FROM Inventory.ItemBlendStatusLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemVendorAudit', MAX(DateUpdated) FROM Inventory.ItemVendorAudit
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitRecipeLine', MAX(DateUpdated) FROM Inventory.KitRecipeLine
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','KitRecipeToItemLocation', MAX(DateUpdated) FROM Inventory.KitRecipeToItemLocation
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemVendor', MAX(DateUpdated) FROM Inventory.ItemVendor
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Inventory','ItemVendorDiscount', MAX(DateUpdated) FROM Inventory.ItemVendorDiscount
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','ItemGroupCategoryDetail', MAX(DateUpdated) FROM Purchasing.ItemGroupCategoryDetail
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','CategoryDetailSegmentUserData', MAX(DateUpdated) FROM Purchasing.CategoryDetailSegmentUserData
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','CategoryDetail', MAX(DateUpdated) FROM Purchasing.CategoryDetail
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','CategoryDetailTypeLookup', MAX(DateUpdated) FROM Purchasing.CategoryDetailTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorLocationGroupOrderPointThresholdToLocation', MAX(DateUpdated) FROM Purchasing.VendorLocationGroupOrderPointThresholdToLocation
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorLocationGroupOrderPointThreshold', MAX(DateUpdated) FROM Purchasing.VendorLocationGroupOrderPointThreshold
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','BuyerGroup', MAX(DateUpdated) FROM Purchasing.BuyerGroup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','ShipmentMethod', MAX(DateUpdated) FROM Purchasing.ShipmentMethod
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','PurchaseOrderNoteTypeLookup', MAX(DateUpdated) FROM Purchasing.PurchaseOrderNoteTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorOrderPointThreshold', MAX(DateUpdated) FROM Purchasing.VendorOrderPointThreshold
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','TransmissionMethodLookup', MAX(DateUpdated) FROM Purchasing.TransmissionMethodLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorLocationOrderDeadline', MAX(DateUpdated) FROM Purchasing.VendorLocationOrderDeadline
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorOrderPointThresholdUnit', MAX(DateUpdated) FROM Purchasing.VendorOrderPointThresholdUnit
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','ReplenishmentFrequencyLookup', MAX(DateUpdated) FROM Purchasing.ReplenishmentFrequencyLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorMoqItemGroupThreshold', MAX(DateUpdated) FROM Purchasing.VendorMoqItemGroupThreshold
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','VendorMoqItemGroupThresholdToItem', MAX(DateUpdated) FROM Purchasing.VendorMoqItemGroupThresholdToItem
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','BuyerGroupToIdsUser', MAX(DateUpdated) FROM Purchasing.BuyerGroupToIdsUser
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','PurchaseOrderNote', MAX(DateUpdated) FROM Purchasing.PurchaseOrderNote
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'Purchasing','PurchaseOrderToPurchaseOrderNote', MAX(DateUpdated) FROM Purchasing.PurchaseOrderToPurchaseOrderNote
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'warehouse','DivertTypeLookup', MAX(DateUpdated) FROM warehouse.DivertTypeLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'warehouse','PickCapability', MAX(DateUpdated) FROM warehouse.PickCapability
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'warehouse','PickCapabilityLookup', MAX(DateUpdated) FROM warehouse.PickCapabilityLookup
INSERT INTO #ModifiedDates (SchemaName, TableName, MaxModifiedDate) SELECT 'warehouse','Divert', MAX(DateUpdated) FROM warehouse.Divert
*/
SELECT * FROM #ModifiedDates
ORDER BY SchemaName, TableName

DROP TABLE IF EXISTS #ModifiedDates
